"""
Plain-language explanations of common Android and iOS app permissions.

This is a fixed list written by hand rather than generated by Claude: the
meaning of a permission doesn't change from app to app, so a curated list is
free, instant and gives the same answer every time. Permissions not in the list
are shown as "not in our list yet" instead of guessed at.

Risk levels describe what the permission could expose if misused:
  High:   very personal data or control (messages, microphone, precise location,
          contacts, health, controlling other apps).
  Medium: personal but more limited data (camera, photos, approximate location).
  Low:    little personal data (internet access, notifications, vibration).
"""

from typing import NamedTuple


class Permission(NamedTuple):
    platform: str     # "Android" or "iOS"
    title: str        # short plain-language name
    explanation: str  # one or two sentences, no jargon
    risk_level: str   # "Low", "Medium" or "High"


# Android: names as they appear in AndroidManifest.xml and on store pages.
_ANDROID = {
    "ACCESS_FINE_LOCATION": ("Precise location", "Can see exactly where you are, accurate to a few metres, using GPS.", "High"),
    "ACCESS_COARSE_LOCATION": ("Approximate location", "Can see roughly where you are, about the size of a neighbourhood.", "Medium"),
    "ACCESS_BACKGROUND_LOCATION": ("Location while closed", "Can see your location even when you aren't using the app.", "High"),
    "CAMERA": ("Camera", "Can take photos and record video while the app is open.", "Medium"),
    "RECORD_AUDIO": ("Microphone", "Can record sound from your microphone.", "High"),
    "READ_CONTACTS": ("Read your contacts", "Can see the names, numbers and emails of everyone in your contacts.", "High"),
    "WRITE_CONTACTS": ("Change your contacts", "Can add, edit or delete people in your contacts.", "Medium"),
    "GET_ACCOUNTS": ("See your accounts", "Can see the list of accounts on your phone, such as your email addresses.", "Medium"),
    "READ_CALENDAR": ("Read your calendar", "Can see your calendar events, including who you meet and where.", "Medium"),
    "WRITE_CALENDAR": ("Change your calendar", "Can add, edit or delete calendar events.", "Low"),
    "READ_CALL_LOG": ("Read your call history", "Can see who you called, who called you, and when.", "High"),
    "WRITE_CALL_LOG": ("Change your call history", "Can add or delete entries in your call history.", "Medium"),
    "PROCESS_OUTGOING_CALLS": ("See outgoing calls", "Can see the numbers you dial and redirect or end calls.", "High"),
    "READ_PHONE_STATE": ("Phone status and identity", "Can see your phone's network, whether you're on a call, and device identifiers.", "Medium"),
    "READ_PHONE_NUMBERS": ("Your phone number", "Can read the phone number(s) of your SIM card.", "Medium"),
    "CALL_PHONE": ("Make phone calls", "Can start phone calls without you dialling, which could cost money.", "Medium"),
    "ANSWER_PHONE_CALLS": ("Answer calls", "Can answer incoming phone calls.", "Medium"),
    "SEND_SMS": ("Send text messages", "Can send text messages, which could cost money.", "High"),
    "RECEIVE_SMS": ("Receive text messages", "Can read text messages as they arrive, including login codes.", "High"),
    "READ_SMS": ("Read your text messages", "Can read all text messages stored on your phone.", "High"),
    "RECEIVE_MMS": ("Receive picture messages", "Can read picture and multimedia messages as they arrive.", "Medium"),
    "READ_EXTERNAL_STORAGE": ("Read your files", "Can read photos, videos and other files stored on your phone.", "Medium"),
    "WRITE_EXTERNAL_STORAGE": ("Change your files", "Can save, change or delete files stored on your phone.", "Medium"),
    "MANAGE_EXTERNAL_STORAGE": ("All files access", "Can read, change and delete almost every file on your phone.", "High"),
    "READ_MEDIA_IMAGES": ("Your photos", "Can see the photos stored on your phone.", "Medium"),
    "READ_MEDIA_VIDEO": ("Your videos", "Can see the videos stored on your phone.", "Medium"),
    "READ_MEDIA_AUDIO": ("Your audio files", "Can see music and other audio files on your phone.", "Low"),
    "BODY_SENSORS": ("Body sensors", "Can read health sensors such as your heart rate.", "High"),
    "BODY_SENSORS_BACKGROUND": ("Body sensors while closed", "Can read health sensors such as heart rate even when you aren't using the app.", "High"),
    "ACTIVITY_RECOGNITION": ("Physical activity", "Can tell whether you're walking, running, cycling or driving, and count steps.", "Medium"),
    "BLUETOOTH_SCAN": ("Find nearby Bluetooth devices", "Can scan for nearby Bluetooth devices, which can reveal where you are.", "Medium"),
    "BLUETOOTH_CONNECT": ("Connect to Bluetooth devices", "Can connect to Bluetooth devices you've paired, like headphones.", "Low"),
    "NEARBY_WIFI_DEVICES": ("Find nearby Wi-Fi devices", "Can find and connect to nearby Wi-Fi devices.", "Medium"),
    "POST_NOTIFICATIONS": ("Notifications", "Can show you notifications.", "Low"),
    "INTERNET": ("Internet access", "Can send and receive data over the internet. Almost every app has this.", "Low"),
    "ACCESS_NETWORK_STATE": ("See network connections", "Can see whether you're online and on Wi-Fi or mobile data.", "Low"),
    "ACCESS_WIFI_STATE": ("See Wi-Fi details", "Can see details of the Wi-Fi network you're connected to.", "Low"),
    "RECEIVE_BOOT_COMPLETED": ("Start when the phone starts", "Can start running in the background as soon as your phone turns on.", "Low"),
    "WAKE_LOCK": ("Keep the phone awake", "Can stop your phone from going to sleep, which can drain the battery.", "Low"),
    "VIBRATE": ("Vibration", "Can make your phone vibrate.", "Low"),
    "FOREGROUND_SERVICE": ("Run in the background", "Can keep working in the background while showing a notification.", "Low"),
    "USE_BIOMETRIC": ("Fingerprint or face unlock", "Can ask you to confirm with your fingerprint or face. The app gets a yes or no, not your fingerprint.", "Low"),
    "SYSTEM_ALERT_WINDOW": ("Display over other apps", "Can draw on top of other apps, which can be used to trick you into tapping things.", "High"),
    "BIND_ACCESSIBILITY_SERVICE": ("Accessibility control", "Can read everything on your screen and tap for you. Very powerful; only needed by assistive apps.", "High"),
    "REQUEST_INSTALL_PACKAGES": ("Install other apps", "Can ask to install other apps from outside the app store.", "High"),
    "QUERY_ALL_PACKAGES": ("See your installed apps", "Can see the list of every app installed on your phone.", "Medium"),
}

# Android permissions defined by Google Play services rather than Android itself.
_ANDROID_FULL_NAMES = {
    "com.google.android.gms.permission.AD_ID": (
        "Advertising ID",
        "Can read your phone's advertising ID, which ad companies use to track you across apps.",
        "Medium",
    ),
}

# iOS: the Info.plist keys an app must declare before asking for access.
_IOS = {
    "NSCameraUsageDescription": ("Camera", "Can take photos and record video.", "Medium"),
    "NSMicrophoneUsageDescription": ("Microphone", "Can record sound from your microphone.", "High"),
    "NSPhotoLibraryUsageDescription": ("Your photos", "Can see the photos and videos you allow (all of them, or a selection you pick).", "Medium"),
    "NSPhotoLibraryAddUsageDescription": ("Save to your photos", "Can save new photos and videos to your library, but not see the existing ones.", "Low"),
    "NSLocationWhenInUseUsageDescription": ("Location while using", "Can see your location while you're using the app.", "Medium"),
    "NSLocationAlwaysAndWhenInUseUsageDescription": ("Location at all times", "Can see your location even when you aren't using the app.", "High"),
    "NSLocationAlwaysUsageDescription": ("Location at all times", "Can see your location even when you aren't using the app (older iOS versions).", "High"),
    "NSContactsUsageDescription": ("Your contacts", "Can see the names, numbers and emails of people in your contacts.", "High"),
    "NSCalendarsUsageDescription": ("Your calendar", "Can see and change your calendar events.", "Medium"),
    "NSRemindersUsageDescription": ("Your reminders", "Can see and change your reminders.", "Low"),
    "NSBluetoothAlwaysUsageDescription": ("Bluetooth", "Can find and connect to nearby Bluetooth devices, which can reveal where you are.", "Medium"),
    "NSHealthShareUsageDescription": ("Read health data", "Can read the health data you allow, such as steps, heart rate or sleep.", "High"),
    "NSHealthUpdateUsageDescription": ("Write health data", "Can add data to the Health app.", "Medium"),
    "NSMotionUsageDescription": ("Motion and fitness", "Can read your movement data, such as steps and whether you're walking or driving.", "Medium"),
    "NSFaceIDUsageDescription": ("Face ID", "Can ask you to confirm with Face ID. The app gets a yes or no, not your face data.", "Low"),
    "NSSpeechRecognitionUsageDescription": ("Speech recognition", "Can turn your speech into text; the audio may be sent to Apple to do this.", "Medium"),
    "NSUserTrackingUsageDescription": ("Tracking across apps", "Asks to track what you do in other companies' apps and websites, usually for advertising.", "High"),
    "NSLocalNetworkUsageDescription": ("Local network", "Can find and talk to devices on your home or office network.", "Medium"),
    "NSAppleMusicUsageDescription": ("Media library", "Can see your music and media library.", "Low"),
    "NSHomeKitUsageDescription": ("Smart home", "Can see and control your smart home devices.", "Medium"),
    "NSSiriUsageDescription": ("Siri", "Can work with Siri and send it requests.", "Low"),
    "NFCReaderUsageDescription": ("NFC", "Can read NFC tags held near your phone.", "Low"),
}

ANDROID_PREFIX = "android.permission."


def _build_catalog() -> dict[str, Permission]:
    """One lookup table keyed by the full permission name."""
    catalog = {ANDROID_PREFIX + short: Permission("Android", *info) for short, info in _ANDROID.items()}
    catalog.update({name: Permission("Android", *info) for name, info in _ANDROID_FULL_NAMES.items()})
    catalog.update({name: Permission("iOS", *info) for name, info in _IOS.items()})
    return catalog


CATALOG = _build_catalog()
